// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sql2GoogleDrive.DAL.TaskContext;

namespace Sql2GoogleDrive.DAL.Migrations
{
    [DbContext(typeof(JobContext))]
    [Migration("20201026134824_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.Connection", b =>
                {
                    b.Property<int>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AuthSql")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AuthWindows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.DayToRun", b =>
                {
                    b.Property<int>("DayToRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Friday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Saturday")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sunday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Thursday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("INTEGER");

                    b.HasKey("DayToRunId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("DayToRun");
                });

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.TimeToRun", b =>
                {
                    b.Property<int>("TimeToRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeToRunId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("TimeToRun");
                });

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.DayToRun", b =>
                {
                    b.HasOne("Sql2GoogleDrive.DAL.TaskContext.Schedule", null)
                        .WithMany("RunAtDays")
                        .HasForeignKey("ScheduleId");
                });

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.Job", b =>
                {
                    b.HasOne("Sql2GoogleDrive.DAL.TaskContext.Connection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId");

                    b.HasOne("Sql2GoogleDrive.DAL.TaskContext.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");
                });

            modelBuilder.Entity("Sql2GoogleDrive.DAL.TaskContext.TimeToRun", b =>
                {
                    b.HasOne("Sql2GoogleDrive.DAL.TaskContext.Schedule", null)
                        .WithMany("TimeToRun")
                        .HasForeignKey("ScheduleId");
                });
#pragma warning restore 612, 618
        }
    }
}
